### ISSUE TITLE
Logos not showing for Atlas pages on Android phone

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#24]
See https://photos.app.goo.gl/oY8ddoJZg3fNbt5W6

**Comment by burkmarr** [comment]
Actually this problem was evident on desktop too, but you would not have noticed unless you cleared your browser cache. Looking at the code, the bug crept in a couple of weeks back when we upgraded the website from Drupal 9 to Drupal 10. At that time we had to refactor code that used deprecated PHP functions and this bug passed in unoticed then (unoticed probably due to browser caching of images). It is fixed now.

**Comment by sacrevert** [comment]
Cheers. Was fully expecting it to be Drupal 10 related!
