### ISSUE TITLE
Koenigia islandica - missing text

### ISSUE THREAD

**Issue by tangiblegains** [BiologicalRecordsCentre/bsbi-atlas-drupal8#31]
Some of the text that is present in the book is missing in the online account. Specifically, first para, "....whilst on Skye it occurs in the Carex demissa - K. islandica flush community (Rodwell, 1991)." Note Rodwell 1991, not 1992, which is displayed on the website. 
I'm a bit concerned that some of the text/corrections finalised for the book didn't make it across to the website, so logging these errors is worthwhile.

**Comment by sacrevert** [comment]
@kwal2 to check that this is correct in the DDb. 
Given that this is not an erratum for the book (as I understand it), and will be updated on the website whenever we upload a new set of captions, then this issue can be closed when it is certain that the DDb is correct because there will be no need to list website errata in the erratum document once they are updated (unlike for the book obviously).

**Comment by sacrevert** [comment]
There is an error in the DDb caption (a missing HTML tag closing some italics), and some missing text, but I have corrected these myself. There is still the problem with Rodwell Mires and Heaths appearing as 1992 rather than 1991, but I will open another issue for that and close this one.

**Comment by burkmarr** [comment]
Done.

**Comment by tangiblegains** [comment]
Thanks Oli and Rich.


Dr Peter Stroh
Scientific & England Officer
Botanical Society of Britain and Ireland (BSBI)
Cambridge University Botanic Garden
1 Brookside
Cambridge CB2 1JE

email: ***@***.***
tel: 01223 762054 or 07981 572678
