### ISSUE TITLE
Downloads for non-map images 

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#6]
Implement PNG/SVG downloads for other images on website, including copyright statement as per existing map downloads.

Decisions to be made about interface for choice when >1 image on page as per apparency/phenology and trends

**Comment by sacrevert** [comment]
This worked for a phenology plot on my phone, but didn't have the pop-up copyright agreement statement that we have for the maps. Can we implement this for all download buttons please?

**Comment by burkmarr** [comment]
I actually misinterpreted your original request for 'copyright statement' as a request to add the attribution. Then I was confused by your comment because I have popups disabled on my browser, so I hadn't seen that popup for ages and had forgotten all about it! It begs the question of whether or not a popup is the best way to do this if it doesn't even appear for users who have their popups disabled.

**Comment by sacrevert** [comment]
I think the attribution is better. I don't think we have the funds/time to worry about  the current pop-up solution for the data download. I'm inclined to leave it and close this issue ultimately
